[package]
name = "squeeb"
version = "0.1.0"
authors = ["Kaitlyn Richardson <kaitlyn@thryse.com>"]
edition = "2018"

[dependencies]
byteorder = "^1.3"
enum-primitive-derive = "^0.1"
num-traits = "^0.1"